name: Audit

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  audit:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name: Run tests
      run: go test ./...

    - name: Echo secret to a file
      run: echo "${{ vars.CONFIG }}" >> ./configs/a.yaml

    - name: Tree project
      run: tree -aI